# -*- coding: utf-8 -*-
"""GoogleMaps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lLjrrtWlB8VXk9mf6Ml4c4VqrID1mopi
"""

!pip install googlemaps
!pip install gmplot

import googlemaps
from datetime import datetime

# Configurar tu API key de Google Maps
api_key = ''  # Reemplaza 'YOUR_GOOGLE_MAPS_API_KEY' con tu clave de API de Google Maps
gmaps = googlemaps.Client(key=api_key)

# Definir las coordenadas del punto central
latitude = -3.96
longitude = -81.24
central_point = (latitude, longitude)

# Buscar lugares dentro de un radio de 5 km
places_result = gmaps.places_nearby(location=central_point, radius=28000)

# Filtrar los resultados y obtener detalles de los lugares
places_within_radius = []
for place in places_result['results']:
    place_details = gmaps.place(place_id=place['place_id'])
    places_within_radius.append({
        "name": place_details['result']['name'],
        "coords": (
            place_details['result']['geometry']['location']['lat'],
            place_details['result']['geometry']['location']['lng']
        ),
        "address": place_details['result'].get('vicinity', 'No address available')
    })

# Mostrar los lugares encontrados
for place in places_within_radius:
    print(f"Name: {place['name']}, Coordinates: {place['coords']}, Address: {place['address']}")

# Para agregar estos lugares al mapa usando gmplot
from gmplot import gmplot

# Crear el objeto gmap
gmap = gmplot.GoogleMapPlotter(latitude, longitude, 13, apikey=api_key)

# Añadir un marcador para el punto central
gmap.marker(latitude, longitude, title="Punto Central")

# Dibujar un círculo de radio 5 km alrededor del punto central
gmap.circle(latitude, longitude, 28000, color='blue', edge_width=2, face_alpha=0.1)

# Añadir marcadores para los lugares dentro del radio
for place in places_within_radius:
    gmap.marker(place["coords"][0], place["coords"][1], title=place["name"], color='red')

# Guardar el mapa en un archivo HTML
gmap.draw("map.html")

# Mostrar el mapa en el notebook
from IPython.display import IFrame
IFrame('map.html', width=800, height=600)
